version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=tech4humans
      - POSTGRES_PASSWORD=tech4humans
      - POSTGRES_DB=webapp
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
