version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=tech4humans
      - POSTGRESQL_PASSWORD=tech4humans
      - POSTGRESQL_DATABASE=webapp
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
